### ISSUE TITLE
请问，本地测试正常，部署之后，在登录界面登录时出现“系统内部错误”，浏览器查看错误日志如下

### ISSUE THREAD

**Issue by heikesheng** [mindskip/xzs-mysql#397]
Uncaught (in promise) 用户未登录
Uncaught (in promise) Error: Navigation cancelled from "/index" to "/login" with a new navigation.      
    at He (chunk-vendors.6c7b90f9.js:39:17852)
    at Re (chunk-vendors.6c7b90f9.js:39:17586)
    at chunk-vendors.6c7b90f9.js:39:22140
    at i (chunk-vendors.6c7b90f9.js:39:17168)
    at i (chunk-vendors.6c7b90f9.js:39:17206)
    at Le (chunk-vendors.6c7b90f9.js:39:17214)
    at chunk-vendors.6c7b90f9.js:39:22095
    at i (chunk-vendors.6c7b90f9.js:39:17168)
    at chunk-vendors.6c7b90f9.js:39:17196
    at chunk-vendors.6c7b90f9.js:39:22006

**Comment by alvis-u** [comment]
这是后端的问题，发下后台日志

**Comment by heikesheng** [comment]
> 这是后端的问题，发下后台日志
您好，这是start1.log的日志：
2022-04-13 13:11:35.606  INFO 8994 --- [           main] com.mindskip.xzs.XzsApplication          : Starting XzsApplication v3.6.0 on cloud-model-10649 with PID 8994 (/usr/local/xzs-3.6.0.jar started by root in /usr/local)
2022-04-13 13:11:35.608  INFO 8994 --- [           main] com.mindskip.xzs.XzsApplication          : The following profiles are active: prod
2022-04-13 13:11:37.164  WARN 8994 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-04-13 13:11:37.189  INFO 8994 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2022-04-13 13:11:37.189  INFO 8994 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1538 ms
2022-04-13 13:11:38.636  INFO 8994 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: any request, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@26abb146, org.springframework.security.web.context.SecurityContextPersistenceFilter@6f01b95f, org.springframework.security.web.header.HeaderWriterFilter@4d1bf319, org.springframework.web.filter.CorsFilter@72c8e7b, org.springframework.security.web.authentication.logout.LogoutFilter@5b799640, com.mindskip.xzs.configuration.spring.security.RestLoginAuthenticationFilter@505fc5a4, org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter@1807e3f6, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@1a245833, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@7a5ceedd, org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter@f1da57d, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@65f8f5ae, org.springframework.security.web.session.SessionManagementFilter@5c80cf32, org.springframework.security.web.access.ExceptionTranslationFilter@4f32a3ad, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@4722ef0c]
2022-04-13 13:11:38.963  INFO 8994 --- [           main] org.xnio                                 : XNIO version 3.3.8.Final
2022-04-13 13:11:38.971  INFO 8994 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.8.Final
2022-04-13 13:11:39.037  INFO 8994 --- [           main] o.s.b.w.e.u.UndertowServletWebServer     : Undertow started on port(s) 8000 (http) with context path ''
2022-04-13 13:11:39.040  INFO 8994 --- [           main] com.mindskip.xzs.XzsApplication          : Started XzsApplication in 4.13 seconds (JVM running for 4.9)
~

**Comment by heikesheng** [comment]
确实是后端MySQL的问题，我配置有误，多谢多谢啦~
